name: Deploy

on:
  push:
    branches: [ main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: deploy-formbricks-dev
    steps:
    - uses: actions/checkout@v3
    - uses: astappiev/docker-compose-remote-action@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: ${{ secrets.DEPLOY_HOST }}
        ssh_user: ${{ secrets.DEPLOY_USERNAME }}
        ssh_private_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        ssh_host_public_key: ${{ secrets.DEPLOY_PUBLIC_KEY }}
        docker_compose_prefix: myapp
